name: ${artifactId}
version: ${version}
main: dev.cerus.hardcorehearts.HardcoreHeartsPlugin
author: Cerus
api-version: 1.17

commands:
  hardcorehearts:
    permission: "hardcorehearts.command"
    description: "Hardcore Hearts"
    usage: "/hardcorehearts [toggle]"